name: platform_v2
description: "Org Builder"

publish_to: 'none'

version: 2.0.2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.2.0
  flutter_riverpod: ^2.6.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  cloud_firestore: ^5.6.0
  flutter_svg: ^2.2.0
  logging: ^1.3.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_dropzone: ^4.2.1
  dotted_border: ^3.0.1
  data_table_2: ^2.5.15
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  custom_lint: ^0.7.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
